### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by despoinamusica39** [aliarslanansari/itunes-react#1]
hello!!!pleaseeeeeeeeee can you upload all the code complete for using?I have no idea from programming!!!I AM BEGGING YOU...or at least one web link?

**Comment by aliarslanansari** [comment]
You should fork it and then clone the respository
Run the following command to run it locally in development mode
```
npm install
npm start
```

**Comment by aliarslanansari** [comment]
[Live Link](https://itunesmusic.now.sh/)
Link for live Demo

**Comment by despoinamusica39** [comment]
woowwwwwwwwww...Aliar the web link not works!!!please can you check it?

**Comment by aliarslanansari** [comment]
you must install Redux dev tool, as it's a development build 
[Link Google Chrome](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en)
[Link FireFox](https://addons.mozilla.org/en-US/firefox/addon/reduxdevtools/)

**Comment by despoinamusica39** [comment]
woowwwwwwwwwwwwwwwwwwww..........what amazing webbbbbbbbbbbbbbbbbb...pleaseeeeeeeeeeeeeeee can you make it show unlimited results?I am begging youuuuuuuuuuuu...

I found a way to query more records. There is a parameter called offset, which is not mentioned in API documentation.


https://stackoverflow.com/questions/44177089/itunes-search-api-page-number-for-the-query?fbclid=IwAR3ywf5P6k5zdS_NpSmD9hMedPwCeVomEUldfgKsCJ5DJqu77k_Eyvp6yBA

**Comment by despoinamusica39** [comment]
Please Aliar!!!I will preciate it so muchhhhhhhhhhhh

**Comment by aliarslanansari** [comment]
**Just remove the "limit" parameter from the api URL**

**Comment by despoinamusica39** [comment]
ufff my good friend how?can you do it please?

**Comment by aliarslanansari** [comment]
[Check Out this branch](https://github.com/aliarslanansari/itunes-react/tree/fetch_all)

**Comment by aliarslanansari** [comment]
[API](https://github.com/aliarslanansari/itunes-react/blob/1d4a58ba2d4bc1606f17e9d2d622c1712348306e/src/api/index.js#L7)
